### ISSUE TITLE
Als ein <Mitarbeiter>, will ich <die Adressen der Kunden als Etikette in ein PDF abspeichern können>, sodass ich <sie ausdrucken und verwenden kann>

### ISSUE THREAD

**Issue by Che4ter** [Che4ter/specialized-subscription-management-system#28]
**Tasks**

**Akzeptanzkriterium**
- [ ] Adressen aller Kunden als PDF ausdrucken
- [ ] Adressen aller **aktiven** Kunden als PDF ausdrucken
- [ ] Adressen aller Kunden mit **offenen** Rechnungen Kunden als PDF ausdrucken
