### ISSUE TITLE
Als <Entwickler>, will ich <ein Visual Studio Projekt ausetzten>, sodass ich <eine gute Startgrundlage habe>.

### ISSUE THREAD

**Issue by Che4ter** [Che4ter/specialized-subscription-management-system#40]
Entwicklungsprojekt im Visual Studio oder Visual Studio Code ausetzen.

**Tasks**
- [x] Entscheidung Visual Studio oder Visual Studio Code
- [x] Installation Entwicklungsungebung
- [x] Erstellung von Template Projekt
- [x] Zu Github hinzufügen

**Akzeptanzkriterium**
- [x] Lauffähiges Example Projekt
- [x] Projekt in Github Repo commited
