### ISSUE TITLE
Als <Entwickler>, will ich <mein Dashboard auf einem Template aufbauen>, sodass ich <mich nicht um UI kümmern muss>

### ISSUE THREAD

**Issue by Che4ter** [Che4ter/specialized-subscription-management-system#41]
**Tasks**
- [x] Entscheid welches Template verwendet werden soll
  - [ ] https://github.com/pixinvent/robust-free-bootstrap-admin-template
  - [ ] https://github.com/akveo/blur-admin
- [x] Integration Template in Example Projekt

**Akzeptanzkriterium**
- [x] Lauffähiges Example Projekt Basierend auf Template

**Comment by Che4ter** [comment]
- Templates erwiesen sich als schwierig zu integrieren
- Es wird neu das MUI CSS Framwork mit dem Flex Grid von jeroenooms verwendet
