### ISSUE TITLE
Als ein <Entwickler>, will ich <die Applikation auf einer Stating Platform betreiben>, sodass ich <unter realen Bedingungen testen kann>.

### ISSUE THREAD

**Issue by Che4ter** [Che4ter/specialized-subscription-management-system#43]
**Tasks**
- [ ] Erstellen eines Azure Accounts
- [ ] Einrichten einer Staging Plattform
- [ ] Deployen auf Staging
**Akzeptanzkriterium**
- [ ] Applikation läuft auf einer Staging Plattform bei Azure
